version: 2.1

jobs:
  build:
    description: "Build with Emacs 26.3 org-mode 9.2.2"
    docker:
      - image: "labn/org-rfc"
    working_directory: ~/project
    steps:
      - checkout
      - run:
          command: "make"
      - run:
          command: "make test"
      - run:
          command: "make idnits"
      - store_artifacts:
          path: ~/project/publish
